 CREATE TABLE `users` (                                                                                                                                                                                                                                                                                                                                                                              
          `id` int(10) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                             
          `username` char(50) NOT NULL DEFAULT '',                                                                                                                                                                                                                                                                                                                                                          
          `passwd` char(50) NOT NULL DEFAULT '',                                                                                                                                                                                                                                                                                                                                                            
          `cookie` char(100) NOT NULL DEFAULT '',                                                                                                                                                                                                                                                                                                                                                           
          `webchat_id` char(50) NOT NULL DEFAULT '',                                                                                                                                                                                                                                                                                                                                                        
          `create_time` datetime NOT NULL,                                                                                                                                                                                                                                                                                                                                                                  
          PRIMARY KEY (`id`),                                                                                                                                                                                                                                                                                                                                                                               
          UNIQUE KEY `webchat_id` (`webchat_id`)                                                                                                                                                                                                                                                                                                                                                            
        ) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8        